import { z } from "zod";

export const CATEGORY_KEYS = [
  "campus",
  "dormitories",
  "classrooms",
  "libraries",
  "city",
] as const;
export const TAG_KEYS = [
  "dormitory",
  "sports",
  "laboratories",
  "student_life",
  "architecture",
  "outdoor",
  "indoor",
] as const;
export const Category = z.enum(CATEGORY_KEYS);
export const Tag = z.enum(TAG_KEYS);
export const WebUrl = z
  .string()
  .max(4096)
  .url()
  .refine((v) => {
    const u = new URL(v);
    return (
      ["https:", "http:"].includes(u.protocol) && !u.username && !u.password
    );
  }, "Expected a public HTTP(S) URL");

// LEVEL 1: metadata sent to the AI provider, alongside actual image bytes in a separate part.
export const ImageAssessmentInput = z
  .object({
    university_name: z.string().min(1).max(250),
    image_url: WebUrl,
    image_context: z.string().max(14000),
  })
  .strict();

// LEVEL 2: generated by the AI provider for ONE image. Never sent directly to the UI.
export const ImageAssessment = z
  .object({
    category: z.enum(["campus", "dormitory", "classroom", "library", "city"]),
    is_relevant: z.boolean(),
    confidence: z.number().min(0).max(1),
    reasoning: z.string().min(1).max(1600),
    duplicate_risk: z.enum(["low", "medium", "high", "unknown"]),
    tags: z.array(Tag).max(7),
  })
  .strict();
export type Assessment = z.infer<typeof ImageAssessment>;

export const Photo = z.object({
  id: z.string(),
  title: z.string(),
  image_url: WebUrl,
  source: WebUrl,
  date: z.string(),
  date_kind: z.enum(["published", "retrieved"]),
  verification_status: z.enum([
    "verified",
    "limited_verification",
    "source_unavailable",
  ]),
  confidence: z.number().min(0).max(1),
  reasoning: z.string(),
  tags: z.array(Tag),
  category: Category,
  verification_method: z.string(),
  duplicate_risk: z.enum(["low", "medium", "high", "unknown"]),
});
export type PhotoRecord = z.infer<typeof Photo>;
export const Candidate = z.object({
  id: z.string(),
  name: z.string(),
  location: z.string(),
  selection_token: z.string(),
});
export type UniversityCandidate = z.infer<typeof Candidate>;
export const ErrorResult = z.object({
  status: z.literal("error"),
  error_code: z.string(),
  message: z.string(),
});
export const SuccessResult = z.object({
  status: z.literal("success"),
  university_name: z.string(),
  location: z.string(),
  description: z.string(),
  description_sources: z.array(WebUrl),
  categories: z.object({
    campus: z.array(Photo),
    dormitories: z.array(Photo),
    classrooms: z.array(Photo),
    libraries: z.array(Photo),
    city: z.array(Photo),
  }),
  data_quality: z.enum(["complete", "limited"]),
  warnings: z.array(z.string()),
  missing_categories: z.array(Category),
  stats: z.object({
    found: z.number(),
    assessed: z.number(),
    accepted: z.number(),
    duplicates_removed: z.number(),
    rejected: z.number(),
    unavailable: z.number(),
    elapsed_ms: z.number(),
  }),
  diagnostics: z
    .object({
      candidates_selected: z.number(),
      page_fetches: z.number(),
      page_reuses: z.number(),
      download_failed: z.number(),
      ai_failed: z.number(),
      first_photo_ms: z.number().nullable(),
      budget_exhausted: z.boolean(),
    })
    .optional(),
  generated_at: z.string(),
});
// LEVEL 3: the backend's final discriminated union, consumed by the frontend switch.
export const ProfileResult = z.discriminatedUnion("status", [
  SuccessResult,
  z.object({
    status: z.literal("disambiguation_needed"),
    query: z.string(),
    candidates: z.array(Candidate),
  }),
  z.object({
    status: z.literal("not_found"),
    query: z.string(),
    suggestions: z.array(z.string()),
  }),
  ErrorResult,
]);
export type Profile = z.infer<typeof SuccessResult>;
export type Result = z.infer<typeof ProfileResult>;
export const Progress = z.object({
  stage: z.enum(["resolving", "searching", "verifying", "organizing"]),
  found: z.number(),
  assessed: z.number(),
  accepted: z.number(),
  elapsed_ms: z.number(),
});
export type ProgressData = z.infer<typeof Progress>;
// Transport envelope only: processing is not a final profile status.
export const JobResponse = z.discriminatedUnion("status", [
  z.object({
    status: z.literal("processing"),
    progress: Progress,
    partial: SuccessResult.optional(),
  }),
  ...ProfileResult.options,
]);
export const SearchRequest = z
  .object({
    university_name: z.string().trim().min(2).max(200),
    selection_token: z.string().max(18000).optional(),
  })
  .strict();
